In [1]:
#넘파이는 파이썬 데이터 사이언스에서 유용히 활용되는 도구를 제공하는 라이브러리이다. 다차원 어레이 배열과 빠른 어레이 연산이 넘파이의 핵심 지원 요소이다.

import numpy as np

In [18]:
#1차원 어레이는 중첩이 없는 리스트와 동일한 모양이다.
#np.array()함수를 적용해 생성 가능하며 Vector 라고도 부른다.

list_1D=[1,17,-7.5,3.14, 2.71828]
arr_1D=np.array(list_1D)

#2차원 어레이의 모든 항목은 동일한 모양의 1차원 어레이어야 한다.
#동일한 길이의 리스트를 항목으로 갖는 중첩 리스트를 2차원 어레이로 변환할 수 있다.

list_2D=[[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]]

arr_2D=np.array(list_2D)

In [7]:
print(f"어레이 출력 >> {arr_1D}")
arr_1D
#변수가 가리키는 리스트와 동일 항목을 갖는 어레이를 가리킨다.

어레이 출력 >> [ 1.      17.      -7.5      3.14     2.71828]


array([ 1.     , 17.     , -7.5    ,  3.14   ,  2.71828])

In [20]:
print(f"2차원 어레이 출력 >> \n{arr_2D}")
arr_2D

2차원 어레이 출력 >> 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
#위의 1차원 어레이의 데이터 타입은 float이다.
print(f"어레이 데이터 타입 출력 >> {arr_1D.dtype}")
arr_1D.dtype
#어레이의 항목들은 통일된 자료형을 가져야하기 떄문이다.

어레이 데이터 타입 출력 >> float64


dtype('float64')

In [22]:
print(f"2차원 어레이 데이터 타입 출력 >> {arr_2D.dtype}")
arr_2D.dtype

2차원 어레이 데이터 타입 출력 >> int64


dtype('int64')

In [23]:
#어레이의 차원을 확인할 때에는 .ndim을 사용한다.
#이 때, 1차원 어레이는 한개의 축, 2차원 어레이는 두개의 축을 지니고 있다.
print(f"어레이 차원 출력 >> {arr_1D.ndim}")
print(f"2차원 어레이 차원 출력 >> {arr_2D.ndim}")

어레이 차원 출력 >> 1
2차원 어레이 차원 출력 >> 2


In [24]:
#어레이의 모양은 shape 속성으로 확인할 수 있다.
#튜플 자료형으로 저장되어있으며 arr_1D는 (5,)의 모양을 갖는다.
print(f"어레이 모양 출력 >> {arr_1D.shape}")
print(f"2차원 어레이의 모양 출력 >> {arr_2D.shape}")
#튜플 자료형은 쉼표가 포함되어있어야 함에 주의한다.

어레이 모양 출력 >> (5,)
2차원 어레이의 모양 출력 >> (3, 4)


In [12]:
#어레이 객체 자료형은 항상 numpy.ndarray이다.
#type() 함수를 이용하여 확인한다.
print(f"어레이 타입 출력 >> {type(arr_1D)}")
type(arr_1D)

어레이 타입 출력 >> <class 'numpy.ndarray'>


numpy.ndarray

In [25]:
print(f"2차원 어레이 타입 출력 >> {type(arr_2D)}")
type(arr_2D)

2차원 어레이 타입 출력 >> <class 'numpy.ndarray'>


numpy.ndarray

In [17]:
#range()함수와 달리 np.arange()는 부동소수점 스텝 사용이 가능하다.
#항상 오른쪽 끝값 이전까지만 반복 적용한다.
print(f"np.arange값 출력 >> {np.arange(0,1,0.1)}")
np.arange(0,1,0.1)

np.arange값 출력 >> [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
#reshape() 매서드는 주어진 어레이의 모양을 원하는대로 변경한다.

arr_1D_8=np.arange(8)
arr_1D_8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr_1D_8.reshape(2,4) #정수 인자를 받아서 모양을 변경
arr_1D_8.reshape((2,4)) #튜플로 인자를 받아서 모양 변경

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
#어레이의 모양을 지정할 때 튜플은 특정 위치에 -1을 사용할 수 있다.
#그 위치의 값은 튜플의 다른 항목 정보를 이용하여 자동 결정 된다.

arr_1D_20=np.arange(20) #0~19 까지의 벡터를 만든다.
arr_1D_20.reshape((5,-1)) #5개 행으로 20개의 숫자를 나열해야하므로 -1을 4로 결정한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
arr_1D_20.reshape((-1,4)) #-1은 4개의 열을 만들어야하므로 -1->5로 결정된다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
#2.5부터 시작하여 0.5씩 증가하는 값으로 구성된 어레이
#단, 5.0 이전까지 생성한다.

import numpy as np

arr_1D_5=np.arange(2.5,5,0.5)

arr_1D_5

array([2.5, 3. , 3.5, 4. , 4.5])

In [37]:
#해당 어레이의 자료형, 차원, 모양을 출력하는 코드를 작성하라 

print(f"자료형 >> {arr_1D_5.dtype}")
print(f"차원 >> {arr_1D_5.ndim}")
print(f"모양 >> {arr_1D_5.shape}")

자료형 >> float64
차원 >> 1
모양 >> (5,)


In [38]:
#2차원 어레이의 모양과 차원을 출력하는 코드를 작성하라

student_grade=[[85,92,78],
               [90,88,95],
               [76,85,80],
               [88,90,92]]
student_grade=np.array(student_grade)

print(f"2차원 어레이 출력 >> \n {student_grade}")
print(f"모양 >> {student_grade.shape}")
print(f"차원 >> {student_grade.ndim}")

2차원 어레이 출력 >> 
 [[85 92 78]
 [90 88 95]
 [76 85 80]
 [88 90 92]]
모양 >> (4, 3)
차원 >> 2


In [40]:
mixed_list=[10,20,3.14,40]
#위의 리스트를 넘파이 어레이로 변환하고 출력한 뒤
#자료형이 결정된 이유를 설명하라
mixed_arr=np.array(mixed_list)
print(f"mixed_arr >> \n{mixed_arr}")
print(f"자료형 >> {mixed_arr.dtype}")
#넘파이 어레이는 자료형을 통일한다.
#float 자료형이 결정된 까닭은 자료형 통합 시에
#자료가 훼손되면 안되기 때문에, 가장 큰 허용범위를 지닌
#자료형으로 자료형이 통일된 것이다.

mixed_arr >> 
[10.   20.    3.14 40.  ]
자료형 >> float64


In [41]:
#np.arange(1,13)을 이용해 1차원 어레이를 생성하라
arr_1D_12=np.arange(1,13)

In [43]:
#생성한 어레이를 3행 4열의 어레이로 변형하여 저장하라
arr_2D_a=arr_1D_12.reshape((3,4))

In [44]:
#생성한 어레이를 -1행 2열의 모양으로 변형하여 저장하라
arr_2D_b=arr_1D_12.reshape(-1,2)

In [48]:
#2차원 어레이 a, b와 모양, 차원, 크기를 각각 출력하라
print(f"어레이 a >>\n{arr_2D_a}")
print(f"모양 >> {arr_2D_a.shape}")
print(f"차원 >> {arr_2D_a.ndim}")
print(f"크기 >> {arr_2D_a.size}\n")

print(f"어레이 b >>\n{arr_2D_b}")
print(f"모양 >> {arr_2D_b.shape}")
print(f"차원 >> {arr_2D_b.ndim}")
print(f"크기 >> {arr_2D_b.size}")

어레이 a >>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
모양 >> (3, 4)
차원 >> 2
크기 >> 12

어레이 b >>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
모양 >> (6, 2)
차원 >> 2
크기 >> 12


In [50]:
#변형 전후 크기가 동일한지 확인하라
default_size=arr_1D_12.size
a_size=arr_2D_a.size
b_size=arr_2D_b.size

if(a_size==b_size):
    if(a_size==default_size):
        print(f"어레이의 크기는 {a_size}로 동일하다.")

어레이의 크기는 12로 동일하다.


In [51]:
#부동 소수점으로 구성된 arr_1D의 dtype은 float64이다.
print('arr_1D:', arr_1D)
print("arr_1D dtype:", arr_1D.dtype)

arr_1D: [ 1.      17.      -7.5      3.14     2.71828]
arr_1D dtype: float64


In [54]:
#float64는 넘파이 어레이가 각각의 부동 소수점을 저장하기 위해서 64비트의 공간을 할당한다는 의미이다.
#1바이트 == 8비트
print(f"항목 자료형 >> {arr_1D.dtype}")
print(f"어레이 크기(byte) >> {arr_1D.nbytes}")

항목 자료형 >> float64
어레이 크기(byte) >> 40


In [55]:
#어레이 항목 하나가 차지하는 메모리 크기는 itemsize
#어레이 포함 항목 개수는 size
#nbytes를 아래와 같이 계산할 수도 있다.
print(f"각 항목별 크기(바이트) >> {arr_1D.itemsize}")
print(f"항목 개수 >> {arr_1D.size}")
print(f"전체 크기(바이트) >> {arr_1D.itemsize*arr_1D.size}")

각 항목별 크기(바이트) >> 8
항목 개수 >> 5
전체 크기(바이트) >> 40


In [58]:
#그러나 항목의 개수가 많은 머신러닝 중 딥러닝에서는
#메모리 사용량을 줄이기 위해 dtype을 지정한다.
arr_1D_16=np.array(list_1D,dtype='float16')
arr_1D_16.dtype

dtype('float16')

In [ ]:
#기존 어레이의 dtype은 astype() 메서드를 통해 변경한다.
arr_1D_16=arr_1D.astype('float16')
arr_1D_16.dtype
#단, 2바이트 안에 다루어지지 않는 소수점은 잘린 뒤 반올림된 형식으로 지정된다.

dtype('float16')

In [60]:
print(f"각 항목 크기(바이트) >> {arr_1D_16.itemsize}")
print(f"항목 수 >> {arr_1D_16.size}")
print(f"전체 크기(바이트) >> {arr_1D_16.itemsize*arr_1D_16.size}")

각 항목 크기(바이트) >> 2
항목 수 >> 5
전체 크기(바이트) >> 10


In [61]:
#arr_2D의 dtype은 정수 자료형인 int64이다.
print(f'arr_2D dtype >> {arr_2D.dtype}')

arr_2D dtype >> int64


In [62]:
#int64는 넘파이가 각각 64비트 크기의 공간을 사용한다는 의미이다.

arr_2D=np.array(list_2D)
print(f"항목 자료형 >> {arr_2D.dtype}")
print(f"어레이 크기(바이트) >> {arr_2D.nbytes}")

항목 자료형 >> int64
어레이 크기(바이트) >> 96


In [63]:
#arr_2D가 가리키는 어레이는 12개의 정수를 포함하며, 하나의 정수가 8바이트 공간을 차지하게 되므로 총 12*8=96
arr_2D.itemsize*arr_2D.size

96

In [64]:
#2차원 어레이 역시 사용량을 줄이기 위해 형식을 제한할 수 있다.
arr_2D_8=np.array(list_2D, dtype='int8')

In [ ]:
arr_2D_8=arr_2D.astype('int8')
#위와 같이 기존 어레이의 dtype 변경도 가능하다.
#항목 포함 정수가 최대 12로 1파이트만으로도 필요 정수를
#다루는 데 충분하다.
#1바이트 허용 정수 -128~127

In [70]:
arr_2D_8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

In [ ]:
#각 항목이 차지하는 메모리 공간이 1/8로 줄었기 때문에
#어레이 차지 메모리 공간 역시 1/8로 축소된다.
print("항목 크기 (바이트):", arr_2D_8.itemsize)
print("항목 수:", arr_2D_8.size)
print("전체 크기 (바이트):", arr_2D_8.itemsize * arr_2D_8.size)

In [71]:
#문자열은 기본적으로 유니코드 처리 된다.
arr_string=np.array(['python','data','numpy'])
arr_string.dtype

dtype('<U6')

In [72]:
#어레이를 생성할 때 dtype='str'를 지정하면 모든 항목을 문자열로 변환한다.
numeric_1D_strings=np.array(list_1D, dtype='str')
numeric_1D_strings.dtype

dtype('<U7')

In [79]:
arr_bool=np.array([True, False, True, True])
arr_bool.dtype#부울 어레이의 항목 자료형은 bool이다.

dtype('bool')

In [80]:
#다음 1차원 정수 어레이의 자료형과 메모리 크기를 확인하라
# 그 후, 어레이의 자료형을 정수형으로 변경한 어레이를 생성하고 메모리 크기를 출력하라
import numpy as np
arr_int=np.array([10,20,30,40,50],dtype='int32')

print(f"자료형 >> {arr_int.dtype}")
print(f"메모리 크기 >> {arr_int.nbytes}")

arr_int_16=arr_int.astype('int16')

print(f"자료형 >> {arr_int_16.dtype}")
print(f"메모리 크기 >> {arr_int_16.nbytes}")


자료형 >> int32
메모리 크기 >> 20
자료형 >> int16
메모리 크기 >> 10


In [82]:
#어레이의 자료형을 확인하고 dtype이 의미하는 바를 설명
words=['apple','banana','strawberry','kiwi']
fruits=np.array(words)

print(f"자료형 >> {fruits.dtype}")
#가장 긴 문자열의 글자 수가 10이기 때문에

자료형 >> <U10


In [83]:
#다음 어레이를 부울 자료형으로 변환한 어레이를 출력하고
#바이트를 비교하라
import numpy as np
arr_scores=np.array([0,85,0,92,-5])
arr_scores_bool=arr_scores.astype('bool')
print(f"변환 전 어레이 >> {arr_scores}")
print(f"변환 전 자료형 >> {arr_scores.dtype}")
print(f"변환 후 어레이 >> {arr_scores_bool}")
print(f"변환 후 자료형 >> {arr_scores_bool.dtype}")

변환 전 어레이 >> [ 0 85  0 92 -5]
변환 전 자료형 >> int64
변환 후 어레이 >> [False  True False  True  True]
변환 후 자료형 >> bool


In [96]:
#이 어레이를 넘파이 어레이로 변환하고, 자료형 유지하라
import numpy as np

mixed_data = [100, 3.14, 'Python']

arr_obj=np.array(mixed_data, dtype=object)
arr_obj.dtype

for i in arr_obj:
    print(f"값 {i}, 자료형 {type(i)}")

값 100, 자료형 <class 'int'>
값 3.14, 자료형 <class 'float'>
값 Python, 자료형 <class 'str'>


In [97]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
#모든 어레이의 합
arr.sum()
#열별 합
print(arr.sum(axis=0))
#행별 합
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [ ]:
#모든 어레이의 평균
arr.mean()
#열별 평균
print(arr.mean(axis=0))
#행별 평균
print(arr.mean(axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [106]:
#모든 어레이의 표준편차
arr.std()
#열별 표준편차
print(arr.std(axis=0))
#행별 표준편차
print(arr.std(axis=1))

[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [108]:
#최소값 있는 인덱스 반환
print(arr.argmin())
#최대값 있는 인덱스 반환
print(arr.argmax())

#행렬 적용 가능

0
5


In [109]:
eng_scores=np.array([69,71,56,76,74,69,80,68,67,66])

#영어 점수 중 최고점과 최저점을 구하라
print(f"영어 최고점 >> {eng_scores.max()}")
print(f"영어 최저점 >> {eng_scores.min()}")

영어 최고점 >> 80
영어 최저점 >> 56


In [111]:
math_scores = np.array([58, 67, 46, 60, 67, 59, 72, 57, 58, 45])
#전체 점수의 총합과 평균을 구하라

print(f"수학 점수 총합 >> {math_scores.sum()}")
print(f"수학 점수 평균 >> {math_scores.mean()}")

수학 점수 총합 >> 589
수학 점수 평균 >> 58.9


In [112]:
scores = np.array([[69, 58], 
                   [71, 67],
                   [56, 46],
                   [76, 60],
                   [74, 67],
                   [69, 59],
                   [80, 72],
                   [68, 57],
                   [67, 58],
                   [66, 45]])

#다음 어레이에서 영어와 수학의 최고 최저값을 구하라
print(f"영어 최고점 >> {scores.max(axis=0)[0]}")
print(f"영어 최저점 >> {scores.min(axis=0)[0]}")
print(f"수학 최고점 >> {scores.max(axis=0)[1]}")
print(f"수학 최저점 >> {scores.min(axis=0)[1]}")


영어 최고점 >> 80
영어 최저점 >> 56
수학 최고점 >> 72
수학 최저점 >> 45


In [113]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

In [119]:
import pandas as pd
data=pd.read_csv(data_url+"iris.csv", delimiter=',', skiprows=1)
data

,5.1,3.5,1.4,.2,Setosa
0,4.9,3.0,1.4,0.2,Setosa
1,4.7,3.2,1.3,0.2,Setosa
2,4.6,3.1,1.5,0.2,Setosa
3,5.0,3.6,1.4,0.2,Setosa
4,5.4,3.9,1.7,0.4,Setosa
...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Virginica
145,6.3,2.5,5.0,1.9,Virginica
146,6.5,3.0,5.2,2.0,Virginica
147,6.2,3.4,5.4,2.3,Virginica


In [115]:
sw=np.loadtxt(data_url+"iris.csv",delimiter=',',skiprows=1, dtype='float32', usecols=1)
print(sw.shape)
print(sw.dtype)

(150,)
float32


In [120]:
plw=np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, usecols=(2,3))

print(plw.ndim)
print(plw.shape)

2
(150, 2)


In [122]:
sl_v=np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, usecols=(0,4), dtype=str)

print(sl_v.dtype)

<U10


In [124]:
sample=np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, usecols=(0,1,2,3))

sample

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [125]:
sample.shape[0]

150