In [1]:
import numpy as np  #넘파이를 np로 임포트

In [2]:
list_1D=[1,17,-7.5,3.14,2.71828]
arr_1D=np.array(list_1D)

In [3]:
arr_1D #list_1D와 동일 항목 지닌 1차원 어레이 가리킴

array([ 1.     , 17.     , -7.5    ,  3.14   ,  2.71828])

In [4]:
arr_1D.dtype #항목 자료형 확인 dtype

dtype('float64')

In [5]:
arr_1D.ndim #어레이의 차원 할당자 ndim
#1차원 어레이의 항목은 왼->오 하나의 방향으로만 이동
#1차원 어레이는 1개의 축만 지님

1

In [6]:
arr_1D.shape #튜플 자료형으로 자신의 모양 저장
#1차원 어레이의 모양은 길이가 1인 튜플
#arr_1D가 가리키는 1차원 어레이는 5개 항목(불변성)

(5,)

요소가 하나인 튜플 선언시 쉼표 없으면 정수형으로 인식하며, 수학적 식에서 괄호는 우선순위 용도이기에 혼동되지 않도록 하기 위함이다.

1차원 배열과 2차원 배열이 있는 경우 (5, )는 벡터 (5, 1)은 행렬이다.

10,20,30,40,50은 일렬 벡터로 들어감 10 20 30 40 50은 세로 5행 가로 1열 구조를 가졌으며, 이는 각 5개의 데이터가 가로 1에 해당하는 특징을 지녔다고 볼 수 있다.

In [7]:
type(arr_1D) #어레이 객체 자료형은 항상 numpy.ndarray

numpy.ndarray

In [8]:
np.arange(10) #0~9사이 정수로 구성된 1차원 어레이 생성
#부동소수점 스텝으로 사용 가능
np.arange(0,1,0.1) #(a,b,c)면 b-c 까지 반복
#np.arange(0,1,0.01)는 0.99까지

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
list_2D=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr_2D=np.array(list_2D) 

In [10]:
arr_2D #길이 4인 3개 중첩 리스트, 2차원 어레이로 변환

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr_2D.ndim #차원은 축의 개수로 지정 가능
#2차원은 좌->우, 상->하 가능해서 2개의 축. 즉 2차원

2

In [12]:
arr_2D.shape  #행과 열을 항목으로 지닌 길이가 2인 튜플
#3행 4열, (3, 4)

(3, 4)

In [13]:
type(arr_2D) #1차원에서 명시한듯 numpy.ndarray임

numpy.ndarray

In [14]:
import numpy as np
arr1=np.arange(2.5,5.0,0.5)
list1=[2.5,3,3.5,4,4.5]

a_data=arr1.dtype
a_ndim=arr1.ndim
a_shape=arr1.shape

print("어레이 : ",arr1)
print("항목 자료형 : ", a_data)
print("차원 : ", a_ndim)
print("모양 : ", a_shape)

어레이 :  [2.5 3.  3.5 4.  4.5]
항목 자료형 :  float64
차원 :  1
모양 :  (5,)


In [15]:
print("numpyarray >> ", arr1)
print("list >> ", list1)  #print시 쉼표 없어지는건 단순히 출력 방식으로 인한 것
#사람이 리스트와 np.array를 구별하기 위한?

numpyarray >>  [2.5 3.  3.5 4.  4.5]
list >>  [2.5, 3, 3.5, 4, 4.5]


In [16]:
print("[" + ", ".join(map(str, arr1)) + "]")

[2.5, 3.0, 3.5, 4.0, 4.5]


In [17]:
print(arr1.tolist())

[2.5, 3.0, 3.5, 4.0, 4.5]


In [18]:

import numpy as np

scores=[[85,92,78],[90,88,95],[76,85,80],[88,90,92]]

arr_scores=np.array(scores)

print("array >>\n",arr_scores)
print("----------------------------")
print("모양 : ", arr_scores.shape)
print("차원 : ",arr_scores.ndim)

array >>
 [[85 92 78]
 [90 88 95]
 [76 85 80]
 [88 90 92]]
----------------------------
모양 :  (4, 3)
차원 :  2


In [19]:
import numpy as np

mixed_list=[10,20,3.14,40]
arr_mixed_list=np.array(mixed_list)

print("변환된 어레이 >> ", arr_mixed_list)
print("항목 자료형 >>", arr_mixed_list.dtype)

#넘파이 어레이는 모든 항목이 동일 자료형으로 통일
#정수항목으로 통일하면 소수점 손실, 따라서 float64

변환된 어레이 >>  [10.   20.    3.14 40.  ]
항목 자료형 >> float64


In [20]:
arr_2D.dtype

dtype('int32')

In [21]:
import numpy as np

arr_1D=np.arange(0.375, 1, 0.125) #조건 만족 어레인지 작성

print("Array : ", arr_1D)
print("Dtype : ", arr_1D.dtype)
print("Ndim : ", arr_1D.ndim)
print("Shape : ", arr_1D.shape)

Array :  [0.375 0.5   0.625 0.75  0.875]
Dtype :  float64
Ndim :  1
Shape :  (5,)


In [22]:
import numpy as np

scores=[[85, 92, 90],
				[68, 76, 78],
				[75, 85, 70],
				[60, 96, 89],
				[98, 95, 100]]

scores_arr=np.array(scores)

print("Array : \n", scores_arr)
print("Shape : ", scores_arr.shape)
print("Ndim : ", scores_arr.ndim)

Array : 
 [[ 85  92  90]
 [ 68  76  78]
 [ 75  85  70]
 [ 60  96  89]
 [ 98  95 100]]
Shape :  (5, 3)
Ndim :  2


In [23]:
import numpy as np

mixed_list=[10,3.25,"ruler"]
mixed_array=np.array(mixed_list)

print("변환된 어레이 >> ",mixed_array)
print("Dtype >> ",mixed_array.dtype)

변환된 어레이 >>  ['10' '3.25' 'ruler']
Dtype >>  <U32


In [24]:
print('arr_1D : ', arr_1D)
print("arr_1D dtype : ",arr_1D.dtype)
print("arr_1D size : ", arr_1D.nbytes)

arr_1D :  [0.375 0.5   0.625 0.75  0.875]
arr_1D dtype :  float64
arr_1D size :  40


In [25]:
import numpy as np

In [26]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

In [27]:
fathers = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=0)
sons = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=1)

In [29]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[11, 12],
              [13, 14]])

X = A + B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Broadcasting이라는 규칙을 통해 자동 처리합니다. 작은 배열을 큰 배열의 크기에 맞춰 늘려서 연산을 가능하게 하는 방식입니다.

예를 들어 [1,2,3]과 [5]를 더한다고 한다면, [5]는 일차원 어레이이기 때문에 값을 복제한 것으로 생각해 [6,7,8]의 결과를 도출합니다.

In [30]:
import numpy as np

A=np.array([1,2,3])
B=np.array([5])

print(A+B)

[6 7 8]


2차원 배열에서도 마찬가지로 1차원 배열일 경우에만 확장시켜 2차원 배열로 생각하여 계산합니다.

import numpy as np

A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([1],
            [2],
            [3],
            [4])

In [ ]:
import numpy as np

A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[1],
           [2],
           [3]])

print(A+B)
#브로드캐스팅 안되는 까닭

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [ ]:
arr=np.array([1,2,3,4])
mask=arr<3

packed=np.packbits(mask)
print(packed)

restored = np.unpackbits(packed)[:len(mask)]
print(restored)
#부울 배열 용량 줄이기 위해서 압축하고 푸는 방식 사용 가능

[192]
[1 1 0 0]


: 

In [ ]:
True and False
np.array([True, False]) and np.array([True, True])
#파이썬 기본 논리 연산자는 배열 사이에서 사용 불가

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
array=[1,2,3,4]
array_bool=[1,4,3,2]

arr=np.array(array)
arr_b=np.array(array_bool)

print(arr&arr_b)
print(arr|arr_b)
print(arr==arr_b)
print(arr!=arr_b)
arr&arr_b
#넘파이에서는 파이썬 기본 비트 연산자 논리 연산자로도 사용 가능

[1 0 3 0]
[1 6 3 6]
[ True False  True False]
[False  True False  True]


array([1, 0, 3, 0])

In [55]:
import numpy as np

# 어레이 생성
arr_C = np.arange(1, 11)

# 논리합(|)과 부정(~) 연산자를 활용한 조건식
# "3 이하이거나 8 이상"은 "~(3 초과 이고 8 미만)"과 동일하지만,
# 문제 조건에 맞춰 직관적으로 작성: (arr_C <= 3) | ~(arr_C < 8)
condition_C = (arr_C <= 3) | ~(arr_C < 8)

print("arr_C:", arr_C)
print("조건 만족 여부:", condition_C)

arr_C: [ 1  2  3  4  5  6  7  8  9 10]
조건 만족 여부: [ True  True  True False False False False  True  True  True]
