In [9]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[11, 12],
              [13, 14]])

X = A + B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Broadcasting이라는 규칙을 통해 자동 처리합니다. 작은 배열을 큰 배열의 크기에 맞춰 늘려서 연산을 가능하게 하는 방식입니다.

예를 들어 [1,2,3]과 [5]를 더한다고 한다면, [5]는 일차원 어레이이기 때문에 값을 복제한 것으로 생각해 [6,7,8]의 결과를 도출합니다.

In [ ]:
import numpy as np

A=np.array([1,2,3])
B=np.array([5])

print(A+B)

[6 7 8]


2차원 배열에서도 마찬가지로 1차원 배열일 경우에만 확장시켜 2차원 배열로 생각하여 계산합니다.

import numpy as np

A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([1],
            [2],
            [3],
            [4])

In [ ]:
import numpy as np

A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[1],
           [2],
           [3]])

print(A+B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [ ]:
arr=np.array([1,2,3,4])
mask=arr<3

packed=np.packbits(mask)
print(packed)

restored = np.unpackbits(packed)[:len(mask)]
print(restored)

[192]
[1 1 0 0]


In [ ]:
True and False
np.array([True, False]) and np.array([True, True])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
array=[1,2,3,4]
array_bool=[1,4,3,2]

arr=np.array(array)
arr_b=np.array(array_bool)

print(arr&arr_b)
print(arr|arr_b)
print(arr==arr_b)
print(arr!=arr_b)
arr&arr_b

[1 0 3 0]
[1 6 3 6]
[ True False  True False]
[False  True False  True]


array([1, 0, 3, 0])

In [ ]:
import numpy as np

# 어레이 생성
arr_C = np.arange(1, 11)

# 논리합(|)과 부정(~) 연산자를 활용한 조건식
# "3 이하이거나 8 이상"은 "~(3 초과 이고 8 미만)"과 동일하지만,
# 문제 조건에 맞춰 직관적으로 작성: (arr_C <= 3) | ~(arr_C < 8)
condition_C = (arr_C <= 3) | ~(arr_C < 8)

print("arr_C:", arr_C)
print("조건 만족 여부:", condition_C)

arr_C: [ 1  2  3  4  5  6  7  8  9 10]
조건 만족 여부: [ True  True  True False False False False  True  True  True]


In [10]:
result=arr1 + 3 < arr2 & ~arr1 * 2 >= arr2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
(((arr1 + 3) < (arr2 & (~arr1 * 2))) >= arr2)

array([False, False, False])

In [26]:
(arr1 + 3 < arr2) & ((~arr1 * 2) >= arr2)

array([False, False, False, False, False])

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = (arr1 + 3 < arr2) & ((~arr1 * 2) >= arr2)

In [5]:
result

array([False, False, False])

In [19]:
arr1 = np.arange(1, 6)
arr1

array([1, 2, 3, 4, 5])

In [20]:
arr2 = np.arange(5, 6, 0.2)
arr2


array([5. , 5.2, 5.4, 5.6, 5.8])

In [40]:
arr2

array([5. , 5.2, 5.4, 5.6, 5.8])

In [ ]:
print(arr1 + 3) #정수 어레이 반환
print(2 >= arr2) #부울 어레이 반환
print(arr2 & ~arr1) #정수와 부동소수점 비교, 오류 발생

[4 5 6 7 8]
[False False False False False]


TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [39]:
(arr1 + 3) < (arr2 & (~arr1 * 2)) >= arr2

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [35]:
check1=~arr1 * 2
print(check1)

[ -4  -6  -8 -10 -12]


In [38]:
print(arr1+3)
print(check1)
print(arr2&check1)

[4 5 6 7 8]
[ -4  -6  -8 -10 -12]


TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [36]:
arr2&check1

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [27]:
(arr1 + 3 < arr2) & ((~arr1 * 2) >= arr2)

array([False, False, False, False, False])