In [3]:
#arr_A와 arr_B를 중첩 리스트를 이용하여 생성하라

import numpy as np

arr_A=np.arange(1,7).reshape((2,3))
arr_B=np.arange(10,70,10).reshape((2,3))

sum_arr=arr_A+arr_B
div_arr=sum_arr/2

print(div_arr)

[[ 5.5 11.  16.5]
 [22.  27.5 33. ]]


In [5]:
arr_c=np.arange(1,11)

condition_c=(arr_c<=3)|~(arr_c<8)

print(arr_c[condition_c])
print(condition_c)

[ 1  2  3  8  9 10]
[ True  True  True False False False False  True  True  True]


In [ ]:
url= 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

pearson=np.loadtxt(url+"pearson_dataset.csv",delimiter=',', skiprows=1, usecols=1)

pearson_cm=pearson/100
print(pearson_cm.dtype)
print(pearson_cm.size)

float64
1078


array([1.519, 1.605, 1.608, ..., 1.76 , 1.76 , 1.702], shape=(1078,))

In [10]:
pearfather=np.loadtxt(url+'pearson_dataset.csv', delimiter=',', skiprows=1, usecols=0)

pear_bool=(pearfather<170)&(pearson>=180)

pear_bool.shape

(1078,)

In [20]:
array=np.arange(36).reshape(6,6)
array_2=np.arange(0,21,4).reshape(6,1)
print(array_2)
array+array_2

[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]
 [20]]


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
base=np.arange(1,13).reshape((4,3))
add_col=np.array([0,10,20])
arr_step1=base+add_col

add_row=np.array([[0],[100],[200],[300]])
arr_step2=arr_step1+add_row

print(base)
print(arr_step1)
print(arr_step2)
print(arr_step2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1 12 23]
 [ 4 15 26]
 [ 7 18 29]
 [10 21 32]]
[[  1  12  23]
 [104 115 126]
 [207 218 229]
 [310 321 332]]
(4, 3)


In [26]:
pearson = np.loadtxt(url+"pearson_dataset.csv", delimiter=',', skiprows=1)

mean_pearson=pearson.mean(axis=0)

In [28]:
pearson_minus=pearson-mean_pearson
pearson_minus.mean(axis=0)

array([1.59588689e-13, 4.83116330e-13])

In [ ]:
#인덱싱을 적용하는 축은 차원이 1 줄어들지만 슬라이싱은 차원이 줄어들지 않는다.